#!name=三联中读VIP解锁 + 去推广
#!desc=匿名登录自动 7 天会员 + 去除推荐推广词，脚本自托管（Quantumult X 版）
#!author=ddgksf2013 + Aioneas
#!homepage=https://github.com/Aioneas/Surge
#!icon=https://raw.githubusercontent.com/Aioneas/Surge/main/Icon/sanlianzhongdu.png

^https?:\/\/apis\.lifeweek\.com\.cn\/api\/cueWord\/recommend url reject
^https?:\/\/apis\.lifeweek\.com\.cn\/index\/receiveExperienceVip url script-response-body https://raw.githubusercontent.com/Aioneas/Surge/main/Script/sanlianzhongdu.vip.js
^https?:\/\/apis\.lifeweek\.com\.cn\/reg\/vistorRegister\.do url script-request-body https://raw.githubusercontent.com/Aioneas/Surge/main/Script/sanlianzhongdu.vip.js

[MITM]
hostname = apis.lifeweek.com.cn
